spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

google.oauth.client-id=${GOOGLE_CLIENT_ID:913313676574-m0goem1u6dri2jnserrrskvne0g17bku.apps.googleusercontent.com}

file.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB